// Roteiros prontos. Os versículos são referências ("sl 23 1-3") resolvidas na Bíblia ACF
// na hora de usar; os avisos são textos livres que o operador pode editar.
window.PRESETS_PRONTOS = [
  {
    nome: 'Culto de Domingo',
    descricao: 'Boas-vindas, chamada à adoração, avisos, ofertas e bênção final.',
    eventos: [
      { tipo: 'texto', titulo: 'Sejam bem-vindos!', texto: 'Que alegria ter você conosco na casa do Senhor.' },
      { ref: 'sl 122 1' },
      { ref: 'sl 100 4' },
      { ref: 'sl 133 1' },
      { ref: 'hb 10 25' },
      { tipo: 'texto', titulo: 'Avisos', texto: 'Edite este aviso com a programação da semana.' },
      { ref: 'ml 3 10' },
      { ref: '2co 9 7' },
      { ref: 'nm 6 24-26' },
      { tipo: 'fundo' },
    ],
  },
  {
    nome: 'Santa Ceia',
    descricao: 'Palavras da instituição da Ceia e textos sobre o pão da vida.',
    eventos: [
      { tipo: 'texto', titulo: 'Santa Ceia do Senhor', texto: 'Fazei isto em memória de mim.' },
      { ref: '1co 11 23-24' },
      { ref: '1co 11 25-26' },
      { ref: '1co 11 27-28' },
      { ref: 'lc 22 19-20' },
      { ref: 'jo 6 35' },
      { ref: 'jo 6 51' },
      { tipo: 'fundo' },
    ],
  },
  {
    nome: 'Batismo',
    descricao: 'A grande comissão e o significado do batismo.',
    eventos: [
      { tipo: 'texto', titulo: 'Culto de Batismo', texto: 'Celebrando a nova vida em Cristo.' },
      { ref: 'mt 28 19-20' },
      { ref: 'mc 16 16' },
      { ref: 'at 2 38' },
      { ref: 'rm 6 3-4' },
      { ref: 'gl 3 27' },
      { ref: '2co 5 17' },
      { tipo: 'fundo' },
    ],
  },
  {
    nome: 'Casamento',
    descricao: 'Textos sobre aliança, amor e união.',
    eventos: [
      { tipo: 'texto', titulo: 'Celebração de Casamento', texto: 'Edite com os nomes dos noivos.' },
      { ref: 'gn 2 24' },
      { ref: 'rt 1 16' },
      { ref: 'ec 4 9-10' },
      { ref: 'ec 4 12' },
      { ref: '1co 13 4-5' },
      { ref: '1co 13 6-7' },
      { ref: 'mc 10 9' },
      { tipo: 'fundo' },
    ],
  },
  {
    nome: 'Oração e Intercessão',
    descricao: 'Promessas sobre oração para momentos de clamor.',
    eventos: [
      { tipo: 'texto', titulo: 'Momento de Oração', texto: 'Clama a mim, e responder-te-ei.' },
      { ref: 'jr 33 3' },
      { ref: 'sl 145 18' },
      { ref: 'mt 7 7' },
      { ref: 'fp 4 6-7' },
      { ref: 'tg 5 16' },
      { ref: '1ts 5 17' },
    ],
  },
  {
    nome: 'Dízimos e Ofertas',
    descricao: 'Textos para o momento de contribuição.',
    eventos: [
      { tipo: 'texto', titulo: 'Dízimos e Ofertas', texto: 'Adorando a Deus também com nossos bens.' },
      { ref: 'ml 3 10' },
      { ref: 'pv 3 9-10' },
      { ref: '2co 9 7' },
      { ref: 'lc 6 38' },
      { ref: 'mt 6 21' },
    ],
  },
  {
    nome: 'Culto de Consolo',
    descricao: 'Esperança e consolo para cultos fúnebres e momentos de luto.',
    eventos: [
      { tipo: 'texto', titulo: 'Culto de Consolo', texto: 'Bem-aventurados os que choram, porque eles serão consolados.' },
      { ref: 'jo 11 25-26' },
      { ref: 'sl 23 4' },
      { ref: 'jo 14 1-2' },
      { ref: '1ts 4 13-14' },
      { ref: '2co 5 1' },
      { ref: 'ap 21 4' },
    ],
  },
  {
    nome: 'Culto de Jovens',
    descricao: 'Textos para encontros de jovens e adolescentes.',
    eventos: [
      { tipo: 'texto', titulo: 'Culto de Jovens', texto: 'Ninguém despreze a tua mocidade.' },
      { ref: '1tm 4 12' },
      { ref: 'ec 12 1' },
      { ref: 'sl 119 9' },
      { ref: 'pv 3 5-6' },
      { ref: '2tm 2 22' },
    ],
  },
  {
    nome: 'Natal',
    descricao: 'O nascimento de Jesus.',
    eventos: [
      { tipo: 'texto', titulo: 'Feliz Natal!', texto: 'Hoje vos nasceu o Salvador.' },
      { ref: 'is 9 6' },
      { ref: 'mt 1 23' },
      { ref: 'lc 2 10-11' },
      { ref: 'lc 2 14' },
      { ref: 'jo 3 16' },
    ],
  },
  {
    nome: 'Páscoa',
    descricao: 'Morte e ressurreição de Cristo.',
    eventos: [
      { tipo: 'texto', titulo: 'Ele Vive!', texto: 'Não está aqui, porque já ressuscitou.' },
      { ref: 'is 53 5' },
      { ref: 'mt 28 5-6' },
      { ref: '1co 15 3-4' },
      { ref: 'rm 6 9' },
      { ref: '1pe 1 3' },
    ],
  },
];
